timeout: 0
/kernel-x86_64
    protocol: limine
    path: boot():/kernel.elf
    resolution: 1920x1080
    randomize_hhdm_base: yes
    cmdline: logging: { serial: { enable: true } }

    module_path: boot():/kernel_symbols.mod
    module_cmdline: symbols

<<<<<<< HEAD
    module_path: boot():/fs_img
    module_cmdline: fs_img
=======
    module_path: boot():/ramdisk
    module_cmdline: ramdisk
>>>>>>> origin/main
