// CITATION: Generated by ChatGPT

#ifndef _FREESTDDEF_H
#define _FREESTDDEF_H

/* Common types */
typedef unsigned long size_t;
typedef long ptrdiff_t;
typedef int wchar_t;

/* NULL macro */
#ifndef NULL
#define NULL ((void*)0)
#endif

/* offsetof macro */
#define offsetof(type, member) ((size_t)&(((type*)0)->member))

#endif /* _FREESTDDEF_H */