// CITATION: Generated by ChatGPT

#ifndef _FREESTDINT_H
#define _FREESTDINT_H

/* Fixed-width integer types */
typedef signed char        int8_t;
typedef short              int16_t;
typedef int                int32_t;
typedef long long          int64_t;

typedef unsigned char      uint8_t;
typedef unsigned short     uint16_t;
typedef unsigned int       uint32_t;
typedef unsigned long long uint64_t;

/* Optional: intptr_t / uintptr_t */
typedef long               intptr_t;
typedef unsigned long      uintptr_t;

#endif /* _FREESTDINT_H */