name: PR - Format Check
on: [pull_request]
jobs:
  fmt:
    name: Format Check
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
