name: PR - Format Check
on: [pull_request]
jobs:
  fmt:
    name: Format Check
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo fmt
        shell: nix develop --command bash -e {0}
        run: cargo fmt --all -- --check
