name: Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install nightly Rust toolchain
              uses: dtolnay/rust-toolchain@nightly
              with:
                  targets: x86_64-unknown-none,aarch64-unknown-none
                  components: rust-src

            - name: Install QEMU
              run: |
                  sudo apt-get update
                  sudo apt-get install -y qemu-system-x86 qemu-system-arm

            - name: Run all tests
              run: |
                  cargo buildtool test --target x86-64
                  cargo buildtool test --target aarch64

            - name: Upload cached testing directory on failure
              if: ${{ failure() }}
              uses: actions/upload-artifact@v4
              with:
                  name: buildtool-cache-testing
                  path: buildtool-cache/testing
                  if-no-files-found: warn
